Audio dev 2
acoustic-warfare/beamforming-lk pull request #88
Opened 2024-07-25 13:36 UTC by tuvabjornberg

Live audio wonky... 
Wav & MP3 godlike

2024-07-25 13:44 UTC, Karlkorv requested changes
Inge pointers!

2024-07-25 13:44 UTC, Karlkorv commented on src/audio/audio_wrapper.cpp
> + * The callback function portaudio continuously runs to process audio.
jarrå

2024-07-25 13:44 UTC, Karlkorv commented on src/audio/audio_wrapper.cpp
> +    return paContinue;
v nice

2024-07-25 13:44 UTC, Karlkorv commented on src/aw_control_unit.cpp
> +    client_.PublishMessage("sensor/heading", std::to_string(90.0));// Currently not a real value
```suggestion
    client_.PublishMessage("sensor/heading", std::to_string(90.0)); // Currently not a real value
```

2024-07-25 13:44 UTC, Karlkorv commented on src/audio/audio_wrapper.h
> +    AudioWrapper(Pipeline *pipeline, bool debug);
kan nog ta bort debug-boolen egentligen

2024-07-25 13:44 UTC, Karlkorv commented on src/awpu.cpp
> +    audioWrapper = new AudioWrapper(pipeline);
red alert red alert, denna behöver faktiskt fixas

2024-07-25 13:44 UTC, Karlkorv commented
Du leakar också WARA PS mqtt-lösenord vilket känns lite oskönt

2024-07-25 14:07 UTC, tuvabjornberg commented on src/audio/audio_wrapper.h
> +    AudioWrapper(Pipeline *pipeline, bool debug);
fixad i [a99bbe3](https://github.com/acoustic-warfare/beamforming-lk/pull/88/commits/a99bbe3f6dca6a0414eb3b588543c7e7de801840)

2024-07-26 07:15 UTC, tuvabjornberg commented on src/awpu.cpp
> +    audioWrapper = new AudioWrapper(pipeline);
fix i [c2fbe1b](https://github.com/acoustic-warfare/beamforming-lk/pull/88/commits/c2fbe1bb1bd5ed94e532e563b6756bc96305bc0e)

2024-07-29 08:14 UTC, Karlkorv reviewed
Se kommentarer

2024-07-29 08:14 UTC, Karlkorv commented on config.yaml
> -SAMPLE_RATE: 48828.0 #16276.0 #48828.0
:)

2024-07-29 08:14 UTC, Karlkorv commented on daemon.conf
kan vi lägga denna i `audio/`?

2024-07-29 08:14 UTC, Karlkorv commented on src/aw_control_unit.cpp
> +    if (USE_AUDIO) {
stoppar vi audio gracefully? Känns som att det borde finnas en sånhär på slutet också

2024-07-29 09:14 UTC, tuvabjornberg commented on src/aw_control_unit.cpp
> +    if (USE_AUDIO) {
[bb882d7](https://github.com/acoustic-warfare/beamforming-lk/pull/88/commits/bb882d79795f2db315bb05f173b0b74b07c94702) ??

2024-07-29 12:34 UTC, Karlkorv approved these changes
LGTM

2024-07-29 12:35 UTC, merged